# Generated by Django 4.1.3 on 2023-03-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_leave',
            name='emp_id',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Employee_leave',
        ),
    ]
