# Generated by Django 4.1.3 on 2023-03-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employee_employee_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_list', models.FileField(upload_to='static/files')),
                ('catalogue', models.FileField(upload_to='static/files')),
                ('hybrid_vegitable_price', models.FileField(upload_to='static/files')),
            ],
        ),
    ]
