# Generated by Django 4.1.3 on 2023-03-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_leave',
            name='emp_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'manager'), (3, 'employee')], default=1, max_length=50),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Employee_leave',
        ),
    ]
